IdentityApp/ViewModels/RoleAssignViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityApp.ViewModels
{
    public class RoleAssignViewModel
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Exist { get; set; }
    }
}

IdentityApp/ViewModels/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityApp.ViewModels
{
    public class RoleViewModel
    {
        [Display(Name ="Rol ismi")]
        [Required(ErrorMessage ="Rol ismi gereklidir")]
        public string Name { get; set; }
        public string Id { get; set; }
    }
}

IdentityApp/ViewModels/UserViewModel.cs
using IdentityApp.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityApp.ViewModels
{
    public class UserViewModel
    {
        [Required(ErrorMessage ="Kullanıcı İsmi Gereklidir!")]
        [Display(Name ="Kullanıcı Adı")]
        public string UserName { get; set; }

        [Display(Name ="Tel No")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage ="E-Posta Adresi Gereklidir!")]
        [Display(Name ="E-Posta Adresiniz")]
        [EmailAddress(ErrorMessage ="E-Posta Adresiniz doğru formatta değildir!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Şifreniz Gereklidir!")]
        [Display(Name = "Şifre")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        
        [Display(Name = "Şehir")]
        public string City { get; set; }

        public string Picture { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Doğum Tarihi")]
        public DateTime? BirthDay { get; set; }

        [Display(Name = "Cinsiyet")]
        public Gender Gender { get; set; }
    }
}

IdentityApp/Controllers/AdminController.cs
using IdentityApp.Models;
using IdentityApp.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityApp.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : BaseController
    {

        public AdminController(UserManager<AppUser> _userManager,RoleManager<AppRole> _roleManager):base(_userManager,null,_roleManager)
        {
        }
        public IActionResult Index()
        {
            return View(userManager.Users.ToList());
        }

        public IActionResult Claims()
        {
            return View(User.Claims.ToList());
        }

        public IActionResult Users()
        {
            return View(userManager.Users.ToList());
        }

        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateRole(RoleViewModel roleViewModel)
        {
            AppRole role = new AppRole();
            role.Name = roleViewModel.Name;
            IdentityResult result = roleManager.CreateAsync(role).Result;
            if(result.Succeeded)
            {
                return RedirectToAction("Roles");
            }
            else
            {
                AddModelError(result);
            }
            return View(roleViewModel);
        }
        public IActionResult Roles()
        {
            return View(roleManager.Roles.ToList());
        }

        public IActionResult RoleDelete(string id)
        {
            AppRole role = roleManager.FindByIdAsync(id).Result;
            if(role!=null)
            {
                IdentityResult result = roleManager.DeleteAsync(role).Result;
              
            }

            return RedirectToAction("Roles");
        }
        public IActionResult RoleUpdate(string id)
        {
            AppRole role = roleManager.FindByIdAsync(id).Result;
            if (role != null)
            {
                return View(role.Adapt<RoleViewModel>());

            }
            return RedirectToAction("Roles");

        }

        [HttpPost]
        public IActionResult RoleUpdate(RoleViewModel roleViewModel)
        {
            AppRole role = roleManager.FindByIdAsync(roleViewModel.Id).Result;
            if (role != null)
            {
                role.Name = roleViewModel.Name;
                IdentityResult result = roleManager.UpdateAsync(role).Result;
                if(result.Succeeded)
                {
                    return RedirectToAction("Roles");
                }
                else
                {
                    AddModelError(result);
                }

            }
            else
            {
                ModelState.AddModelError("", "Güncelleme işlemi başarısız oldu.");
            }
            return RedirectToAction("Roles");

        }

        public IActionResult RoleAssign(string id)
        {
            TempData["userId"] = id;
            AppUser user = userManager.FindByIdAsync(id).Result;
            ViewBag.userName = user.UserName;
            IQueryable<AppRole> roles = roleManager.Roles;
            List<string> userRoles = userManager.GetRolesAsync(user).Result as List<string>;

            List<RoleAssignViewModel> roleAssignViewModels = new List<RoleAssignViewModel>();
            foreach (var role in roles)
            {
                RoleAssignViewModel roleAssign = new RoleAssignViewModel();
                roleAssign.RoleId = role.Id;
                roleAssign.RoleName = role.Name;
                if (userRoles.Contains(role.Name))
                {
                    roleAssign.Exist = true;
                }
                else
                {
                    roleAssign.Exist = false;
                }
                roleAssignViewModels.Add(roleAssign);
            }
            return View(roleAssignViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(List<RoleAssignViewModel> roleAssignViewModels)
        {
            AppUser user = userManager.FindByIdAsync(TempData["userId"].ToString()).Result;

            foreach (var item in roleAssignViewModels)
            {
                if(item.Exist)
                {
                    await userManager.AddToRoleAsync(user, item.RoleName);
                }
                else
                {
                   await userManager.RemoveFromRoleAsync(user, item.RoleName);
                }
            }
            return RedirectToAction("Users");
        }

    }
}

IdentityApp/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Identity;
using IdentityApp.Models;
using IdentityApp.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using IdentityApp.Enums;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net;
using Microsoft.AspNetCore.Hosting;
using System.Security.Claims;

namespace IdentityApp.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        private readonly IWebHostEnvironment webHostEnvironment;

        public MemberController(UserManager<AppUser> _userManager, SignInManager<AppUser> _signInManager, IWebHostEnvironment hostEnvironment):base(_userManager,_signInManager)
        {
           
            webHostEnvironment = hostEnvironment;

        }
        public IActionResult Index()
        {
            AppUser user = currentUser; 
            UserViewModel userViewModel = user.Adapt<UserViewModel>(); // it takes only the properties wich contain the UserViewModel Class

            return View(userViewModel);
        }

        public IActionResult UserEdit()
        {
            AppUser user = currentUser;
            UserViewModel userViewModel = user.Adapt<UserViewModel>();
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userViewModel,IFormFile userPicture)
        {
            ModelState.Remove("Password");
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            if (ModelState.IsValid)
            {
                AppUser user = currentUser;
                string uniqueFileName = null;

                if(userPicture!=null && userPicture.Length>0)
                {
                   

                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "UserPicture");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + userPicture.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        userPicture.CopyTo(fileStream);
                    }

                   
                }

                user.UserName = userViewModel.UserName;
                user.PhoneNumber = userViewModel.PhoneNumber;
                user.Email = userViewModel.Email;
                user.City = userViewModel.City;
                user.BirthDay = userViewModel.BirthDay;
                user.Gender = (int)userViewModel.Gender;
                user.Picture = uniqueFileName;
                IdentityResult result = await userManager.UpdateAsync(user);

                if(result.Succeeded)
                {
                    await userManager.UpdateSecurityStampAsync(user);
                    await signInManager.SignOutAsync();
                    await signInManager.SignInAsync(user, true);
                    ViewBag.success = "true";
                }
                else
                {
                    AddModelError(result);
                }
            }

            return View(userViewModel);
        }
        public IActionResult PasswordChange()
        {
            
            return View();
        }
        
        [HttpPost]
        public IActionResult PasswordChange(PasswordChangeViewModel passwordChangeViewModel)
        {
            if(ModelState.IsValid)
            {
                AppUser user = currentUser; 
                if(user!=null)
                {
                    bool exist = userManager.CheckPasswordAsync(user, passwordChangeViewModel.OldPassword).Result;
                    if(exist)
                    {
                        IdentityResult result= userManager.ChangePasswordAsync(user,passwordChangeViewModel.OldPassword,passwordChangeViewModel.NewPassword).Result;
                        if(result.Succeeded)
                        {
                            userManager.UpdateSecurityStampAsync(user);

                            signInManager.SignOutAsync();
                            signInManager.PasswordSignInAsync(user, passwordChangeViewModel.NewPassword, true, false);
                            ViewBag.success = "true";
                        }
                        else
                        {
                            AddModelError(result);

                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Eski şifreniz yanlış");
                    }
                }
            }
            return View(passwordChangeViewModel);
        }

        public void LogOut()
        {
            signInManager.SignOutAsync();
        }

        public IActionResult AccessDenied(string returnUrl)
        {
            if(returnUrl.ToLower().Contains("violencePage"))
            {
                ViewBag.message = "Erişmeye çalıştığınız sayfa şiddet videoları içerdiğinden dolayı 15 yaşından büyük olmanız gerekmektedir.";
            }
            else if(returnUrl.ToLower().Contains("ankarapage"))
            {
                ViewBag.message = "Bu sayfaya sadece şehir alanı Ankara olan kullanıcılar erişebilir";
            }
            else if (returnUrl.ToLower().Contains("exchange"))
            {
                ViewBag.message = "30 günlük deneme hakkınız sona ermiştir.";

            }
            else
            {
                ViewBag.message = "Bu sayfa erişim izniniz yoktur. Erişim izni almak için site yöneticisiyle görüşün";
            }
            return View();
        }
        
        [Authorize(Roles="manager,admin")]
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Roles = "editor,admin")]
        public IActionResult Editor()
        {
            return View();
        }

        [Authorize(Policy ="AnkaraPolicy")]
        public IActionResult AnkaraPage()
        {
            return View();
        }

        [Authorize(Policy = "ViolencePolicy")]
        public IActionResult ViolencePage()
        {
            return View();
        }

        public async Task<IActionResult> ExchangeRedirect()
        {
            bool result = User.HasClaim(x => x.Type == "ExpireDateExchange");
            if(!result)
            {
                Claim ExpireDateExchange = new Claim("ExpireDateExchange", DateTime.Now.AddDays(30).Date.ToShortDateString(),
                 ClaimValueTypes.String, "Internal");
                await userManager.AddClaimAsync(currentUser, ExpireDateExchange);
                await signInManager.SignOutAsync();
                await signInManager.SignInAsync(currentUser, true);
            }
            return RedirectToAction("Exchange");
        }

        [Authorize(Policy = "ExchangePolicy")]
        public IActionResult Exchange()
        {
            return View();
        }
    }
}

IdentityApp/Views/Admin/Claims.cshtml
@model List<System.Security.Claims.Claim>
@{
    ViewData["Title"] = "Claims";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h4>Claims</h4>
<hr />
<table class="table table-bordered table-striped table-responsive">
    <tr>
        <th>Kim</th>
        <th>Dağıtıcı</th>
        <th>Ad</th>
        <th>Değer</th>
    </tr>
    @foreach (System.Security.Claims.Claim item in Model)
    {
        <tr>
            <td>@item.Subject.Name</td>
            <td>@item.Issuer</td>
            <td>@item.Type</td>
            <td>@item.Value</td>
        </tr>
    }

</table>

IdentityApp/Views/Admin/CreateRole.cshtml
@model IdentityApp.ViewModels.RoleViewModel

@{
    ViewData["Title"] = "CreateRole";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}


<h4>Rol Oluşturma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

IdentityApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Admin sayfasına hoş geldiniz...</h3>

IdentityApp/Views/Admin/RoleAssign.cshtml
@model List<RoleAssignViewModel>
@{
    ViewData["Title"] = "RoleAssign";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Kullanıcıya rol atama(@ViewBag.userName)</h3>
<hr />
<form asp-controller="Admin" asp-action="RoleAssign" method="post">
    @for (int i = 0; i < Model.Count(); i++)
    {
        <div class="form-check">
            <input asp-for="@Model[i].Exist" type="checkbox" class="form-check-input" />
            <label asp-for="@Model[i].RoleId" class="form-check-label">@Model[i].RoleName</label>
            <input asp-for="@Model[i].RoleName" type="hidden" />
            <input asp-for="@Model[i].RoleId" type="hidden" />
        </div>
    }
    <input class="btn btn-success" type="submit" value="rol ata" />
</form>

IdentityApp/Views/Admin/RoleUpdate.cshtml
@model IdentityApp.ViewModels.RoleViewModel

@{
    ViewData["Title"] = "RoleUpdate";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h1>RoleUpdate</h1>

<h4>RoleViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RoleUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input asp-for="Id" type="hidden" />

            <div class="form-group">
                <input type="submit" value="güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

IdentityApp/Views/Admin/Roles.cshtml
@model List<AppRole>
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Roller</h3>
<hr />
<a class="btn btn-info" href="/Admin/CreateRole">Rol Oluştur</a>
<hr />
<table class="table table table-bordered table-striped">
    <tr>
        <th>ID</th>
        <th>Rol İsmi</th>
        <th>Rol İşlemleri</th>
    </tr>
    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Id</td>
       
            <td>@role.Name</td>
            <td>
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <form asp-action="RoleDelete" asp-route-id="@role.Id" method="post">
                            <button class="btn btn-danger"> <i class="fa fa-trash text-white"></i> </button>
                        </form>
                    </div>
                    <div class="col-md-6 col-sm-12">

                        <a class="btn btn-info" asp-action="RoleUpdate" asp-route-id="@role.Id">
                            <i class="fa fa-pencil"></i>
                        </a>
                    </div>
                   
                </div>
               
            </td>
            
        </tr>
    }
</table>

IdentityApp/Views/Admin/Users.cshtml
@model List<AppUser>
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h3>Üyeler</h3>
<table class="table table-bordered table-striped">
        <tr>
            <td>User Id</td>
            <td>User Name</td>
            <td>Email</td>
            <td>Roller</td>
            <td>Rol Atama</td>
        </tr>
        @if (Model.Count==0)
        {
            <tr>
                 <td colspan="3">Hiç bir üye yoktur </td>
              </tr>
        }
        else
        {
            foreach (var user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td user-roles="@user.Id"></td>
                    <td><a class="btn btn-info" asp-action="RoleAssign" asp-route-id="@user.Id">
                        rol atama
                    </a></td>
                </tr>
            }
        }

    </table>

IdentityApp/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <title>@ViewData["Title"] - IdentityAppCourse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/Admin/Index">Admin Ana Sayfa </a>
                    </li>

                </ul>
               

            </div>
        </div>

    </nav>
    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()

            </div>
            <div class="col-md-4">
                <h3>Menü</h3>
                <a class="btn btn-danger btn-block" href="/Admin/Claims">Üye Claims</a>
                <a class="btn btn-danger btn-block" href="/Admin/Users">Üyeler</a>
                <a class="btn btn-danger btn-block" href="/Admin/Roles">Roller</a>
                <a class="btn btn-danger btn-block" asp-action="LogOut" asp-controller="Member" asp-route-returnUrl="/Home/Index">Çıkış</a>
            </div>
        </div>
    </div>
</body>
</html>